### ISSUE TITLE
[Bug] Odd door behavior with the new 1.8 doors.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#12]
As of commit https://github.com/NavidK0/Carbon/commit/0da8f35147fc1efd4dec38482b1917617485f908

The new 1.8 doors have two parts to them instead of being 'whole'. The top part and the bottom part. An easy way to check this is use LWC and add the new doors to the protection list.

```
        chest:
            enabled: true
        furnace:
            enabled: true
        dispenser:
            enabled: true
        wooden_door:
            enabled: true
        iron_door:
            enabled: true
        trap_door:
            enabled: true
        iron_trapdoor:
            enabled: true
        fence_gate:
            enabled: true
        trapped_chest:
            enabled: true
        spruce_door:
            enabled: true
        birch_door:
            enabled: true
        jungle_door:
            enabled: true
        acacia_door:
            enabled: true
        dark_oak_door:
            enabled: true
        spruce_fence_gate:
            enabled: true
        birch_fence_gate:
            enabled: true
        jungle_fence_gate:
            enabled: true
        dark_oak_fence_gate:
            enabled: true
        acacia_fence_gate:
            enabled: true
```

You can lock the top part of the door and the bottom part will not be locked. You have to lock both the top and bottom portion of the door. This does not occur with oak doors, only the new 1.8 doors.

Shouldn't doors be whole instead of in two parts?
