### ISSUE TITLE
Guardians spawning in abundance. 

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#175]
Dev build 54. http://build.true-games.org/job/Carbon/54/

Guardians are spawning in abundance. What I presume is over the vanilla default. I am using default spawn rates set in bukkit and spigot. One of my players noticed many Guardians in an area. When butchering with worldedit/essentials, they killed 250 in about 90 seconds. He also noticed lag when staying at the spawn point area where guardians were spawning. When I checked it out, I killed 100 in a radius of 25 when butchering. 

```
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15
chunk-gc:
  period-in-ticks: 600
  load-threshold: 0
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 0
```

**Comment by mibby** [comment]
Related issue that was closed, but relevant. The spawning seems bugged in my opinion, causing excess stress on the server to calculate all the entities.

https://github.com/NavidK0/Carbon/issues/172

I have not personally noticed any issues with endermite or rabbits. Only guardians.

**Comment by ghost** [comment]
Seem to have large number of guardians spawning as well, also have noticed they seem to drop after one laser is shot...

**Comment by Shevchik** [comment]
Basicly when server wan't to spawn a guardian it will be able to do this because guardian can spawn in water. The default limit is 70 monsters per chunk and temple extends to 6 chunks so i don't see any bug here. Vanilla spawn a tons of guardians as well.

**Comment by mibby** [comment]
@Shevchik This does not seem natural.

Disabled spawning for Guardians, but they still spawn.

```
mobSpawning:
  rabbits: true
  endermites: true
  guardians: false
```

Restarted server, butchered area, guardians still spawn. 

Edit: Regenerating the chunk generated an ocean monument. But should guardians still be spawning with spawning set to disabled? And should they still be spawning if no monument exists in the world?
